if (WIN32)
    set(RXS_OS_WIN ON)
elseif (APPLE)
    set(RXS_OS_APPLE ON)

    if (IOS OR CMAKE_SYSTEM_NAME STREQUAL iOS)
        set(RXS_OS_IOS ON)
    else()
        set(RXS_OS_MACOS ON)
    endif()
else()
    set(RXS_OS_UNIX ON)

    if (ANDROID OR CMAKE_SYSTEM_NAME MATCHES "Android")
        set(RXS_OS_ANDROID ON)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(RXS_OS_LINUX ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL FreeBSD OR CMAKE_SYSTEM_NAME STREQUAL DragonFly)
        set(RXS_OS_FREEBSD ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL OpenBSD)
        set(RXS_OS_OPENBSD ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Haiku")
        set(RXS_OS_HAIKU ON)
    endif()
endif()

if (RXS_OS_WIN)
    add_definitions(-DWIN32 -DRXS_OS_WIN)
elseif(RXS_OS_APPLE)
    add_definitions(-DRXS_OS_APPLE)

    if (RXS_OS_IOS)
        add_definitions(-DRXS_OS_IOS)
    else()
        add_definitions(-DRXS_OS_MACOS)
    endif()

    if (RXS_ARM)
        set(WITH_SECURE_JIT ON)
    endif()
elseif(RXS_OS_UNIX)
    add_definitions(-DRXS_OS_UNIX)

    if (RXS_OS_ANDROID)
        add_definitions(-DRXS_OS_ANDROID)
    elseif (RXS_OS_LINUX)
        add_definitions(-DRXS_OS_LINUX)
    elseif (RXS_OS_FREEBSD)
        add_definitions(-DRXS_OS_FREEBSD)
    elseif (RXS_OS_OPENBSD)
        add_definitions(-DRXS_OS_OPENBSD)
    elseif (RXS_OS_HAIKU)
        add_definitions(-DRXS_OS_HAIKU)
    endif()
endif()

if (WITH_SECURE_JIT)
    add_definitions(-DRXS_SECURE_JIT)
endif()
